apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  storageClassName: nfs  # Musi pasować do nazwy StorageClass
  accessModes:
    - ReadWriteMany      # NFS obsługuje RWX
  resources:
    requests:
      storage: 1Gi